PART     := xc3s1000-4-ft256
DESIGN_NAME = test_codec
TOP_NAME = test_codec

export XST_CPLD_OPTIONS_FILE ?= xst_cpld_options.xst
export XST_FPGA_OPTIONS_FILE ?= xst_fpga_options.xst
export BITGEN_OPTIONS_FILE   ?= bitgen_options.ut
export IMPACT_OPTIONS_FILE   ?= impact_options.txt

include xilinx_rules.mk
