PART     := xc9572xl-10-vq64
DESIGN_NAME = xessjtag
TOP_NAME = xessjtag

export XST_CPLD_OPTIONS_FILE ?= xst_cpld_options.xst
export XST_FPGA_OPTIONS_FILE ?= xst_fpga_options.xst
export BITGEN_OPTIONS_FILE   ?= bitgen_options.ut
export IMPACT_OPTIONS_FILE   ?= impact_options.txt

SIGNATURE = "<5>!"
include xilinx_rules.mk
