HDL_FILES := \
   test_board_core.vhd \
   test_dualport_core.vhd \
   xsasdramcntl.vhd \
   xsasdramcntl_ppintfc.vhd \
   ps2_kbd.vhd \
   ramintfc_core.vhd \
   vga.vhd

include xilinx_rules.mk

