# where to find stuff...
XST_OPTIONS_DIR    ?= $(CURDIR)/../../
IMPACT_OPTIONS_DIR ?= $(CURDIR)/../../
BITGEN_OPTIONS_DIR ?= $(CURDIR)/../

# include the rules to build the Xilinx configuration bitstream, etc.
include xilinx_rules.mk

